crypto/homo/cl/cl.go

crypto/homo/cl: check that the generator g is non-identity

---

.travis.yml

.travis.yml: build tss-example to ensure the example is executable

---

README.md
example/README.md

README.md, example/README.md: update example readme

---

crypto/polynomial/polynomial.go

KS-AMIS-O-03: crypto/polynomial: add comments of NewPolynomial

---

crypto/utils/utils.go
crypto/utils/utils_test.go

KS-AMIS-F-10: crypto/utils: add a lower bound of threshold

---

crypto/matrix/matrix.go
crypto/matrix/matrix_test.go

KS-AMIS-F-04: crypto/matrix: add an upperbound of size of a matrix

---

crypto/homo/cl/cl.go
crypto/homo/cl/cl_test.go

KS-AMIS-F-05: crypto/cl: Add check of parameters prime and safeParameter

---

crypto/zkproof/schnorr.go

KS-AMIS-O-05: crypto/zkproof/schnorr: fix comment

---

crypto/homo/cl/cl.go
crypto/matrix/matrix.go
crypto/utils/utils.go

KS-AMIS-O-08: crypto: fix comments

---

.golangci.yml
example/config/config.go

linter: enable go sec

---

.gitignore
.gitmodules
Makefile
README.md
crypto/commitment/message.pb.go
crypto/homo/cl/message.pb.go
crypto/zkproof/message.pb.go
tools/protoc.mk
vendor/README

Makefile protoc

---

crypto/birkhoffinterpolation/bk.go
crypto/birkhoffinterpolation/bk_test.go
crypto/tss/addshare/newpeer/0_peer_handler.go
crypto/tss/addshare/newpeer/0_peer_handler_test.go
crypto/tss/addshare/newpeer/1_result_handler.go
crypto/tss/addshare/newpeer/1_result_handler_test.go
crypto/tss/addshare/oldpeer/0_peer_handler.go
crypto/tss/addshare/oldpeer/0_peer_handler_test.go
crypto/tss/addshare/oldpeer/1_compute_handler.go
crypto/tss/addshare/oldpeer/1_compute_handler_test.go
crypto/tss/dkg/0_peer_handler.go
crypto/tss/dkg/0_peer_handler_test.go
crypto/tss/dkg/2_verify_handler.go

*: check bk range

---

README.md

README.md: add share usage

---

crypto/bip32/child/hmac_sha512.go
crypto/bip32/child/hmac_sha512_test.go

crypto/bip32: implement hmac sha512

---

crypto/binaryfield/binary_field_test.go

crypto/binaryfield: Add more tests

---

crypto/ot/ot_ext_receiver.go
crypto/ot/ot_ext_sender.go
crypto/ot/ot_test.go
crypto/utils/utils.go
crypto/utils/utils_test.go

crypto/ot: Add more tests

---

crypto/bip32/child/hmac_sha512_test.go

crypto/bip32/child: add hmac tests

---

crypto/bip32/README.md

crypto/bip32: Add reference in README

---

crypto/bip32/README.md
example/README.md

docs: fix typos

---

crypto/ot/ot_receiver.go
crypto/ot/ot_sender.go

crypto/ot: add index into RO2 function to improve security.

---

example/peer/node.go
go.mod

example: not use gogo proto

---

README.md
crypto/tss/README.md

add notice

---

.travis.yml
go.mod
go.sum

go.mod: use 1.17

---

crypto/cggmp/refresh/round_1.go
crypto/zkproof/paillier/nth_rooot.go

crypto/cggmp: revise sign and signSix

---

crypto/cggmp/mta.go
crypto/cggmp/sign/round_4.go
crypto/cggmp/signSix/round_5.go
crypto/cggmp/signSix/round_6.go
crypto/cggmp/signSix/sign_test.go

crypto/cggmp: add more tests

---

crypto/tss/eddsa/frost/signer/round_1.go
crypto/tss/eddsa/frost/signer/round_2.go
crypto/tss/eddsa/frost/signer/signer_test.go

crypto/tss/eddsa: fix a bug: s should mod curveN and adds more tests

---

crypto/tss/eddsa/frost/signer/round_1.go
crypto/tss/eddsa/frost/signer/round_2.go

crypto/tss/eddsa/frost: add a check: trivial signature

---

crypto/tss/ecdsa/cggmp/refresh/refresh_test.go

crypto/tss/ecdsa/cggmp/refresh: improve to more general tests

---

crypto/tss/ecdsa/cggmp/refresh/refresh_test.go

crypto/tss/ecdsa/cggmp/refresh: fix tests

---

.travis.yml

.travis: build for all branches

---

crypto/tss/eddsa/frost/signer/round_1.go

KS-AMC-F-03:  check the output of SHAPoints is nonzero

---

crypto/tss/ecdsa/cggmp/signSix/round_5.go
crypto/tss/ecdsa/cggmp/signSix/round_6.go

KS-AMC-F-07: fix module of mu

---

crypto/elliptic/secp256k1.go
go.mod
go.sum

mod, *: upgrade btcec to v2.2

---

crypto/birkhoffinterpolation/birkhoffinterpolation.go
crypto/birkhoffinterpolation/birkhoffinterpolation_test.go

crypto/birkhoffinterpolation: fix the function: CheckValid

---

crypto/bip32/child/0_initial_handler.go
crypto/bip32/child/child_test.go
crypto/bip32/child/share_manager.go

Modify bip32 output

---

.travis.yml
go.mod

mod: upgrade go to v1.19

---

crypto/ecpointgrouplaw/ecpointgrouplaw_test.go
crypto/elliptic/elliptic_curve.go
crypto/elliptic/p256.go
crypto/elliptic/p256_test.go

crypto/elliptic: support p256 curve

---

crypto/ecpointgrouplaw/point.go

crypto/ecpointgrouplaw/point.go: add types of elliptic curve P256

---

.travis.yml
crypto/tss/ecdsa/cggmp/dkg/dkg_test.go
crypto/tss/ecdsa/cggmp/refresh/refresh_test.go
crypto/tss/ecdsa/cggmp/sign/sign_test.go
crypto/tss/ecdsa/cggmp/signSix/sign_test.go
crypto/tss/ecdsa/gg18/addshare/newpeer/addshare_test.go
crypto/tss/ecdsa/gg18/addshare/oldpeer/addshare_test.go
crypto/tss/ecdsa/gg18/integration/tss_test.go
crypto/tss/ecdsa/gg18/reshare/0_commit_handler_test.go
crypto/tss/ecdsa/gg18/reshare/reshare_test.go
go.mod
types/message/msg_main.go
types/message/msg_main_echo_test.go
types/message/peer.go

This pull request is inspired by https://github.com/getamis/alice/pull/261. Fix the race condition issues

Fix race conditions

---

README.md

add security issue update

---

crypto/bip32/child/child_test.go
crypto/tss/dkg/1_decommit_handler_test.go
crypto/tss/dkg/2_verify_handler_test.go
crypto/tss/dkg/3_result_handler_test.go
crypto/tss/ecdsa/cggmp/dkg/1_decommit_handler_test.go
crypto/tss/ecdsa/cggmp/dkg/2_verify_handler_test.go
crypto/tss/ecdsa/cggmp/dkg/3_result_handler_test.go
crypto/tss/ecdsa/gg18/reshare/0_commit_handler_test.go
crypto/tss/ecdsa/gg18/reshare/1_verify_handler_test.go
crypto/tss/ecdsa/gg18/reshare/2_result_handler_test.go
crypto/tss/ecdsa/gg18/signer/1_enck_handler_test.go
crypto/tss/ecdsa/gg18/signer/2_mta_handler_test.go
crypto/tss/ecdsa/gg18/signer/3_delta_handler_test.go
crypto/tss/ecdsa/gg18/signer/4_proof_ai_handler_test.go
crypto/tss/ecdsa/gg18/signer/5_commit_vi_ai_handler_test.go
crypto/tss/ecdsa/gg18/signer/6_decommit_vi_ai_handler_test.go
crypto/tss/ecdsa/gg18/signer/7_commit_ui_ti_handler_test.go
crypto/tss/ecdsa/gg18/signer/8_decommit_ui_ti_handler_test.go
crypto/tss/ecdsa/gg18/signer/9_si_handler_test.go
crypto/tss/utils.go

*: use common StopPeerManager to avoid data races

---

crypto/tss/ecdsa/cggmp/refresh/refresh.go
crypto/tss/ecdsa/cggmp/refresh/round_3.go
crypto/tss/ecdsa/cggmp/sign/peer.go
crypto/tss/ecdsa/cggmp/sign/round_1.go
crypto/tss/ecdsa/cggmp/sign/sign.go
crypto/tss/ecdsa/cggmp/sign/sign_test.go

* Remove Y dependencies from 4 round signer
* Add Y secret to refresh result for the 6 round signer

cggmp: remove Y dependencies in 4 round signer and add Y secret to refresh result

---

crypto/ecpointgrouplaw/point.go
crypto/tss/eddsa/frost/signer/round_1.go
crypto/tss/eddsa/frost/signer/round_2.go
crypto/tss/eddsa/frost/signer/signer_test.go
crypto/utils/utils.go

Support Taproot Schnorr Signature

---

Makefile

Makefile: define GOPATH
